### ISSUE TITLE
Just Clone and Run `gulp build` return Error.

### ISSUE THREAD

**Issue by ldh0227** [carlosazaustre/angularapp-gulp-boilerplate#3]
Hi.
I just read ur Agile Web Development with Angular.js.
So. I want to test example.

here is my Run env (work on Windows7 64bit)
![node_env](https://cloud.githubusercontent.com/assets/946434/8179915/33775816-1455-11e5-8d42-8dc58040da97.png)

here is error logs.
```
$ gulp build
[18:19:15] Using gulpfile D:\96.Dev\Sublime_prj\angularapp-gulp-boilerplate\Gulpfile.js
[18:19:15] Starting 'templates'...
[18:19:15] Finished 'templates' after 10 ms
[18:19:15] Starting 'compress'...
[18:19:16] Finished 'compress' after 160 ms
[18:19:16] Starting 'copy'...
[18:19:16] Finished 'copy' after 1.86 ms
[18:19:16] Starting 'uncss'...
[18:19:16] Finished 'uncss' after 1.08 ms
[18:19:16] Starting 'build'...
[18:19:16] Finished 'build' after 3.32 μs
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Transform.emit (events.js:87:13)
    at Transform.onerror (D:\96.Dev\Sublime_prj\angularapp-gulp-boilerplate\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:558:12)
    at Transform.emit (events.js:107:17)
    at Transform.<anonymous> (D:\96.Dev\Sublime_prj\angularapp-gulp-boilerplate\node_modules\gulp-useref\index.js:79:42)
    at Array.forEach (native)
    at Transform.<anonymous> (D:\96.Dev\Sublime_prj\angularapp-gulp-boilerplate\node_modules\gulp-useref\index.js:67:35)
    at Array.forEach (native)
    at Transform.<anonymous> (D:\96.Dev\Sublime_prj\angularapp-gulp-boilerplate\node_modules\gulp-useref\index.js:45:36)
    at Array.forEach (native)
```

I don't have any changes.

How can I fix it?

**Comment by francocorreasosa** [comment]
Same error here.
