### ISSUE TITLE
Gulp error

### ISSUE THREAD

**Issue by francocorreasosa** [carlosazaustre/angularapp-gulp-boilerplate#5]
```
[12:55:39] Using gulpfile ~/Desktop/song-game/Gulpfile.js
[12:55:39] Starting 'server'...
[12:55:39] 'server' errored after 1.42 ms
[12:55:39] Error: Invalid glob argument: undefined
    at Gulp.src (/Users/franco/Desktop/song-game/node_modules/vinyl-fs/lib/src/index.js:20:11)
    at Gulp.<anonymous> (/Users/franco/Desktop/song-game/Gulpfile.js:24:7)
    at module.exports (/Users/franco/Desktop/song-game/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/franco/Desktop/song-game/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/franco/Desktop/song-game/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/franco/Desktop/song-game/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:469:11)
```

**Comment by dixon22ma** [comment]
I am presenting the same problem ... we can fix it? try updating the version of the package and nothing

**Comment by LauserK** [comment]
i just sent a pull request with the fixes.
